server:
  error:
    include-message: always
  spring.application.name: device-manager
  port: 81
spring:
  h2:
    console.enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:devmanager
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true